---
- name: Install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: Instala o pip
  package: 
    name: python2-pip
    state: present

- name: Instala o modulo do docker para o python
  pip:
    name: docker-py
